LittleBird.UI/Areas/Admin/Controllers/TweetController.cs
using LittleBird.Model.Option;
using LittleBird.Service.Option;
using LittleBird.UI.Areas.Admin.Models.DTO;
using LittleBird.UI.Areas.Admin.Models.VM;
using LittleBird.Utility;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LittleBird.UI.Areas.Admin.Controllers
{
    public class TweetController : Controller
    {
        TweetService _tweetService;
        AppUserService _appUserService;
        CommentService _commentService;
        
        public TweetController()
        {
            _tweetService = new TweetService();
            _appUserService = new AppUserService();
            _commentService = new CommentService();
        }
        public ActionResult Add()
        {
            AddTweetVM model = new AddTweetVM()
            {
                AppUsers = _appUserService.GetDefault(x => x.Role==Role.Member)
            };
           
           
            return View(model);
        }
        [HttpPost]
        public ActionResult Add(Tweet data, HttpPostedFileBase Image)
        {
            List<string> UploadedImagePaths = new List<string>();

            UploadedImagePaths = ImageUploader.UploadSingleImage(ImageUploader.OriginalProfileImagePath, Image, 1);

            data.ImagePath = UploadedImagePaths[0];

            if (data.ImagePath == "0" || data.ImagePath == "1" || data.ImagePath == "2")
            {
                data.ImagePath = ImageUploader.DefaultProfileImagePath;
                data.ImagePath = ImageUploader.DefaultXSmallProfileImage;
                data.ImagePath = ImageUploader.DefaulCruptedProfileImage;
            }
            else
            {
                data.ImagePath = UploadedImagePaths[1];
                data.ImagePath = UploadedImagePaths[2];
            }


            data.Status = Core.Enum.Status.Active;
            data.PublishDate = DateTime.Now;
            _tweetService.Add(data);
            return Redirect("/Admin/Tweet/List");
        }

        public ActionResult List()
        {
            List<Tweet> model = _tweetService.GetActive();
            return View(model);
        }
        public ActionResult Update(Guid id)
        {
            Tweet tweet = _tweetService.GetByID(id);
            UpdateTweetVM model = new UpdateTweetVM();
            model.Tweet.ID = tweet.ID;
            model.Tweet.ImagePath = tweet.ImagePath;
            model.Tweet.TweetContent = tweet.TweetContent;
            model.Tweet.PublishDate = DateTime.Now;
            List<AppUser> appusermodel = _appUserService.GetDefault(x => x.Role == Role.Member);
            model.AppUsers = appusermodel;
            return View(model);
        }
        [HttpPost]
        public ActionResult Update(TweetDTO data, HttpPostedFileBase Image)
        {

            List<string> UploadedImagePaths = new List<string>();

            UploadedImagePaths = ImageUploader.UploadSingleImage(ImageUploader.OriginalProfileImagePath, Image, 1);

            data.ImagePath = UploadedImagePaths[0];

            Tweet update = _tweetService.GetByID(data.ID);

            if (data.ImagePath == "0" || data.ImagePath == "1" || data.ImagePath == "2")
            {

                if (update.ImagePath == null || update.ImagePath == ImageUploader.DefaultProfileImagePath)
                {
                    update.ImagePath = ImageUploader.DefaultProfileImagePath;
                    
                    update.ImagePath = ImageUploader.DefaultXSmallProfileImage;
                    update.ImagePath = ImageUploader.DefaulCruptedProfileImage;
                }
                else
                {
                    update.ImagePath = update.ImagePath;
                }

            }
            else
            {
                update.ImagePath = UploadedImagePaths[0];
                update.ImagePath = UploadedImagePaths[1];
                update.ImagePath = UploadedImagePaths[2];
            }
            Tweet tweet = _tweetService.GetByID(data.ID);
            tweet.PublishDate = data.PublishDate;
            tweet.TweetContent = data.TweetContent;
            tweet.AppUserID = data.AppUserID;
            tweet.Status = Core.Enum.Status.Updated;
            _tweetService.Update(tweet);

            return Redirect("/Admin/Tweet/List");


        }
        public RedirectResult Delete(Guid id)
        {
            _tweetService.Remove(id);
            return Redirect("/Admin/Tweet/List");
        }

    }
}

LittleBird.UI/Areas/Member/Controllers/CommentController.cs
using LittleBird.Model.Option;
using LittleBird.Service.Option;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LittleBird.UI.Areas.Member.Controllers
{
    public class CommentController : Controller
    {
        CommentService _commentService;
        AppUserService _appUserService;
        LikeService _likeService;
        TweetService _articleService;

        public CommentController()
        {
            _commentService = new CommentService();
            _appUserService = new AppUserService();
            _likeService = new LikeService();
            _articleService = new TweetService();
        }

        public JsonResult AddComment(string userComment, Guid id)
        {

            Comment comment = new Comment();

            comment.AppUserID = _appUserService.FindByUserName(HttpContext.User.Identity.Name).ID;
            comment.TweetID = id;
            comment.Content = userComment;

            bool isAdded = false;
            try
            {
                _commentService.Add(comment);
                isAdded = true;
            }
            catch (Exception ex)
            {
                isAdded = false;
            }

            return Json(isAdded, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetAtricleComment(string id)
        {
            Guid articleID = new Guid(id);

            Comment comment = _commentService.GetDefault(x => x.TweetID == articleID && x.Status == Core.Enum.Status.Active).LastOrDefault();

            return Json(new
            {
                AppUserImagePath = comment.AppUser.UserImage,
                FirstName = comment.AppUser.FirstName,
                LastName = comment.AppUser.LastName,
                CreatedDate = comment.CreatedDate.ToString(),
                Content = comment.Content,
                CommentCount = _commentService.GetDefault(x => x.TweetID == articleID && (x.Status == Core.Enum.Status.Active || x.Status == Core.Enum.Status.Updated)).Count(),
                LikeCount = _likeService.GetDefault(x => x.TweetID == articleID && (x.Status == Core.Enum.Status.Active || x.Status == Core.Enum.Status.Updated)).Count(),
            }, JsonRequestBehavior.AllowGet);
        }

        public JsonResult DeleteComment(Guid id)
        {
            Guid userID = _appUserService.FindByUserName(HttpContext.User.Identity.Name).ID;
            bool isDelete = false;


            if (_commentService.Any(x => x.AppUserID == userID))
            {
                isDelete = true;
                _commentService.Remove(id);
                return Json(isDelete, JsonRequestBehavior.AllowGet);
            }
            else
            {
                isDelete = false;
                return Json(isDelete, JsonRequestBehavior.AllowGet);
            }
        }
    }
}

LittleBird.UI/Areas/Member/Controllers/LikeController.cs
using LittleBird.Model.Option;
using LittleBird.Service.Option;
using LittleBird.UI.Areas.Member.Models.VM;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LittleBird.UI.Areas.Member.Controllers
{
    public class LikeController : Controller
    {

        AppUserService _appUserService;
        LikeService _likeService;
        CommentService _commentService;
        public LikeController()
        {
            _appUserService = new AppUserService();
            _likeService = new LikeService();
            _commentService = new CommentService();
        }
        public JsonResult AddLike(Guid id)
        {
            JsonCommentLikeVM jr = new JsonCommentLikeVM();
            Guid appuserID = _appUserService.FindByUserName(HttpContext.User.Identity.Name).ID;

            if (!(_likeService.Any(x => x.AppUserID == appuserID && x.TweetID == id)))
            {
                Like like = new Like();
                like.TweetID = id;
                like.AppUserID = appuserID;
                _likeService.Add(like);

                //Kullanıcıya gönderilecek mesaj oluşturulur.

                jr.Likes = _likeService.GetDefault(x => x.TweetID == id).Count();
                jr.userMessage = "likes it";
                jr.isSuccess = true;
                jr.Likes = _likeService.GetDefault(x => x.TweetID == id && (x.Status == Core.Enum.Status.Active || x.Status == Core.Enum.Status.Updated)).Count();
                jr.Comments = _commentService.GetDefault(x => x.TweetID == id && (x.Status == Core.Enum.Status.Active || x.Status == Core.Enum.Status.Updated)).Count();
                return Json(jr, JsonRequestBehavior.AllowGet);
            }
            else
            {
                jr.isSuccess = false;
                jr.userMessage = "You've liked this article before!";

                return Json(jr, JsonRequestBehavior.AllowGet);
            }
        }
    }
}

LittleBird.UI/Areas/Member/Controllers/TweetController.cs
using LittleBird.Model.Option;
using LittleBird.Service.Option;
using LittleBird.UI.Areas.Member.Models.DTO;
using LittleBird.UI.Areas.Member.Models.VM;
using LittleBird.Utility;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LittleBird.UI.Areas.Member.Controllers
{
    public class TweetController : Controller
    {
        AppUserService _appUserService;
        LikeService _likeService;
        TweetService _tweetService;
        CommentService _commentService;
        public TweetController()
        {
            _appUserService = new AppUserService();
            _likeService = new LikeService();
            _tweetService = new TweetService();
            _commentService = new CommentService();
        }
        public ActionResult Add()
        {
            Guid userID = _appUserService.FindByUserName(User.Identity.Name).ID;
            List<Tweet> model = _tweetService.GetDefault(x => x.AppUserID == userID && (x.Status == Core.Enum.Status.Active || x.Status == Core.Enum.Status.Updated));
            return View(model);
           
        }
        [HttpPost]
        public ActionResult Add(Tweet data, HttpPostedFileBase Image)
        {
            List<string> UploadedImagePaths = new List<string>();

            UploadedImagePaths = ImageUploader.UploadSingleImage(ImageUploader.OriginalProfileImagePath, Image, 1);

            data.ImagePath = UploadedImagePaths[0];

            if (data.ImagePath == "0" || data.ImagePath == "1" || data.ImagePath == "2")
            {
                data.ImagePath = ImageUploader.DefaultProfileImagePath;
                data.ImagePath = ImageUploader.DefaultXSmallProfileImage;
                data.ImagePath = ImageUploader.DefaulCruptedProfileImage;
            }
            else
            {
                data.ImagePath = UploadedImagePaths[1];
                data.ImagePath = UploadedImagePaths[2];
            }


            AppUser user = _appUserService.GetByDefault(x => x.UserName == User.Identity.Name);
            data.AppUserID = user.ID;
            data.PublishDate = DateTime.Now;

            _tweetService.Add(data);


            return Redirect("/Member/Tweet/Add");


        }
        [HttpPost]
        public ActionResult List()
        {
            Guid userID = _appUserService.FindByUserName(User.Identity.Name).ID;
            List<Tweet> model = _tweetService.GetDefault(x => x.AppUserID == userID && (x.Status == Core.Enum.Status.Active || x.Status == Core.Enum.Status.Updated));
            return View(model);
        }
        public ActionResult List2()
        {
            Guid userID = _appUserService.FindByUserName(User.Identity.Name).ID;
            List<Tweet> model = _tweetService.GetDefault(x => x.AppUserID == userID && (x.Status == Core.Enum.Status.Active || x.Status == Core.Enum.Status.Updated));
            return View(model);
        }
        public ActionResult Update(Guid id)
        {
            AddTweetDTO model = new AddTweetDTO();
            Tweet tweet = _tweetService.GetByID(id);
           
            model.ID= tweet.ID;
        
            model.TweetContent = tweet.TweetContent;
            model.PublishDate = DateTime.Now;
            model.ImagePath= tweet.ImagePath;
          

            return View(model);
        }
        [HttpPost]
        public ActionResult Update(AddTweetDTO data,HttpPostedFileBase Image)
        {

            List<string> UploadedImagePaths = new List<string>();

            UploadedImagePaths = ImageUploader.UploadSingleImage(ImageUploader.OriginalProfileImagePath, Image, 1);

            data.ImagePath = UploadedImagePaths[0];

            Tweet update = _tweetService.GetByID(data.ID);

            if (data.ImagePath == "0" || data.ImagePath == "1" || data.ImagePath == "2")
            {

                if (update.ImagePath == null || update.ImagePath == ImageUploader.DefaultProfileImagePath)
                {
                    update.ImagePath = ImageUploader.DefaultProfileImagePath;
                    update.ImagePath = ImageUploader.DefaultXSmallProfileImage;
                    update.ImagePath = ImageUploader.DefaulCruptedProfileImage;
                }
                else
                {
                    update.ImagePath = update.ImagePath;
                }

            }
            else
            {
                update.ImagePath = UploadedImagePaths[0];
                update.ImagePath = UploadedImagePaths[1];
                update.ImagePath = UploadedImagePaths[2];
            }
            Tweet tweet = _tweetService.GetByID(data.ID);

            tweet.TweetContent = data.TweetContent;
            tweet.PublishDate = data.PublishDate;
            tweet.Status = Core.Enum.Status.Updated;
            _tweetService.Update(tweet);
            return Redirect("/Member/Tweet/List");
        }
        public ActionResult Delete(Guid id)
        {
            _tweetService.Remove(id);
            return Redirect("/Member/Tweet/Add");
        }
        //public ActionResult Show(Guid id)
        //{
        //    TweetDetailVM model = new TweetDetailVM();

        //    model.Tweets = _tweetService.GetActive();

        //    foreach (var item in model.Tweets)
        //    {
        //        model.Comments = _commentService.GetDefault(x => x.TweetID == item.ID).OrderByDescending(x => x.CreatedDate).Take(10).ToList();

        //        model.LikeCount = _likeService.GetDefault(x => x.TweetID == item.ID).Count();
        //        model.CommentCount = _commentService.GetDefault(x => x.TweetID == item.ID).Count();
        //    }



        //    model.Tweet = _tweetService.GetByID(id);
        //    model.AppUser = _appUserService.GetByID(model.Tweet.AppUser.ID);
        //    model.Comments = _commentService.GetDefault(x => x.TweetID == id && (x.Status == Core.Enum.Status.Active || x.Status == Core.Enum.Status.Updated));
        //    model.LikeCount = _likeService.GetDefault(x => x.TweetID == id && (x.Status == Core.Enum.Status.Active || x.Status == Core.Enum.Status.Updated)).Count;
        //    model.CommentCount = _commentService.GetDefault(x => x.TweetID == id && (x.Status == Core.Enum.Status.Active || x.Status == Core.Enum.Status.Updated)).Count;
        //    model.Likes = _likeService.GetDefault(x => x.TweetID == id && (x.Status == Core.Enum.Status.Active || x.Status == Core.Enum.Status.Updated));

        //    return View(model);
       // }
    }


}

LittleBird.UI/Areas/Member/Views/Tweet/Add.cshtml
@{
    ViewBag.Title = "Add";
    ViewBag.Title = "List";
    Layout = "~/Areas/Member/Views/Shared/denemeprofillayoutpage.cshtml";
}

@model List<LittleBird.Model.Option.Tweet>

<script src="~/Content/js/dataTables.bootstrap.min.js"></script>
<script src="~/Content/js/jquery.dataTables.min.js"></script>
<link href="~/Content/css/dataTables.bootstrap.min.css" rel="stylesheet" />


@foreach (var item in Model)
{
    <section class="content">

        <div class="row">

            <div class="col-md-8">
                <div class="nav-tabs-custom">
                    <ul class="nav nav-tabs">
                        <li class=""><a href="#@item.ID" data-toggle="tab" aria-expanded="true">Show</a></li>

                    </ul>


                    <div class="tab-content">
                        <div class="tab-pane" id="@item.ID">
                            <!-- Post -->
                            <div class="post">
                                <div class="user-block">
                                    <img class="img-circle img-bordered-sm" src="@Session["ImagePath"]" alt="user image">
                                    <span class="username">
                                        <a href="#"> @item.AppUser.UserName</a>
                                        <a href="/Member/Tweet/Delete/@item.ID" class="pull-right btn-box-tool"><i class="fa fa-times"></i></a>
                                    </span>
                                    <span class="description">@item.PublishDate</span>


                                    @if (item.ImagePath == "/Content/Uploads/UserImage/CruptedImages/kaan.png")
                                    {
                                        <img src="" style="display:block" width="1" height="1" />

                                    }
                                    else
                                    {
                                        <img src="@item.ImagePath" style="display:block" width="75" height="75" />

                                    }

                                </div>
                                <!-- /.user-block -->



                                @item.TweetContent


                                <ul class="list-inline">
                                    <li><a href="#" class="link-black text-sm"><i class="fa fa-share margin-r-5"></i> Share</a></li>
                                    <li>
                                        <a href="#" class="link-black text-sm"><i class="fa fa-thumbs-o-up margin-r-5"></i> Like</a>
                                    </li>
                                    <li>
                                        <a href="#" class="link-black text-sm"><i class="fa fa-thumbs-o-up margin-r-5"></i>ReTweet</a>
                                    </li>
                                    <li class="pull-right">
                                        <a href="#" class="link-black text-sm">
                                            <i class="fa fa-comments-o margin-r-5"></i> Comments
                                            (5)
                                        </a>
                                    </li>
                                </ul>

                                <input class="form-control input-sm" type="text" placeholder="Type a comment">
                            </div>
                            <!-- /.post -->
                            <!-- Post -->
                            <!-- /.post -->
                            <!-- Post -->
                            <!-- /.post -->
                        </div>
                        <!-- /.tab-pane -->
                        <!-- /.tab-pane -->

                        <div class="tab-pane" id="settings">
                            <form class="form-horizontal">
                                <div class="form-group">
                                    <label for="inputName" class="col-sm-2 control-label">Name</label>

                                    <div class="col-sm-10">
                                        <input type="email" class="form-control" id="inputName" placeholder="Name">
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="inputEmail" class="col-sm-2 control-label">Email</label>

                                    <div class="col-sm-10">
                                        <input type="email" class="form-control" id="inputEmail" placeholder="Email">
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="inputName" class="col-sm-2 control-label">Name</label>

                                    <div class="col-sm-10">
                                        <input type="text" class="form-control" id="inputName" placeholder="Name">
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="inputExperience" class="col-sm-2 control-label">Experience</label>

                                    <div class="col-sm-10">
                                        <textarea class="form-control" id="inputExperience" placeholder="Experience"></textarea>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="inputSkills" class="col-sm-2 control-label">Skills</label>

                                    <div class="col-sm-10">
                                        <input type="text" class="form-control" id="inputSkills" placeholder="Skills">
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div class="col-sm-offset-2 col-sm-10">
                                        <div class="checkbox">
                                            <label>
                                                <input type="checkbox"> I agree to the <a href="#">terms and conditions</a>
                                            </label>
                                        </div>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div class="col-sm-offset-2 col-sm-10">
                                        <button type="submit" class="btn btn-danger">Submit</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                        <!-- /.tab-pane -->
                    </div>




                    <!-- /.tab-content -->
                </div>
                <!-- /.nav-tabs-custom -->
            </div>


            <!-- /.col -->
        </div>


        <!-- /.row -->

    </section>

}

<section class="content">
    <div class="row">
        <!-- left column -->
        <div class="col-md-6">
            <!-- general form elements -->
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">Add Tweet</h3>
                </div>

                <!-- /.box-header -->
                <!-- form start -->
                <a href="~/Areas/Member/Views/Tweet/Add.cshtml"></a>
                <form action="/Member/Tweet/Add" method="post" role="form" enctype="multipart/form-data">
                    <div class="box-body">

                        <div class="form-group">
                            <label for="TweetContent">TweetContent</label>
                            <input type="text" name="TweetContent" class="form-control" placeholder="TweetContent">
                        </div>


                        <div class="form-group">
                            <label for="Image">Image</label>
                            <input type="file" name="Image" value="" class="form-control" />
                        </div>
                    </div>
                    <div class="box-footer">
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>





<script>



    $(function () {

        $('#example1').DataTable()
        $('#example2').DataTable({
            'paging': true,
            'lengthChange': false,
            'searching': false,
            'ordering': true,
            'info': true,
            'autoWidth': false
        })
        $('#activity').add({
            'paging': true,
            'lengthChange': false,
            'searching': false,
            'ordering': true,
            'info': true,
            'autoWidth': false
        })
    })
</script>

LittleBird.UI/Areas/Member/Views/Tweet/List2.cshtml
@{
    ViewBag.Title = "List2";
    Layout = "~/Areas/Member/Views/Shared/denemeprofillayoutpage.cshtml";
}

LittleBird.UI/Areas/Member/Views/Tweet/Show.cshtml
@{
    ViewBag.Title = "Show";
    Layout = "~/Areas/Member/Views/Shared/MemberLayoutPage.cshtml";
}
@model LittleBird.UI.Areas.Member.Models.VM.TweetDetailVM

<section class="content">
    <div class="row">
        <div class="col-md-10">
            @foreach (var item in Model.Tweets)
            {
                <div class="box box-widget">
                    <div class="box-header with-border">
                        <div class="user-block">
                            <img class="img-circle" src="@item.AppUser.UserImage" alt="User Image">
                            <span class="username"><a href="#">@item.AppUser.FirstName @item.AppUser.LastName</a></span>
                            <span class="description"> - @item.PublishDate</span>
                        </div>
                    </div>
                    <div class="box-body" id="articlelist">
                        <img class="img-responsive pad" src="@Model.Tweet.ImagePath" alt="Photo">
                        <p>@Model.Tweet.TweetContent</p>
                        @if (!(Model.Tweet.Likes.Any(x => x.AppUser.UserName == User.Identity.Name)))
                        {
                            string elementID = "message" + Model.Tweet.ID;
                            <button type="button" id="like" onclick="like('@Model.Tweet.ID')" class="btn btn-default btn-xs"><i class="fa fa-thumbs-o-up"></i> Like</button>
                            <span id="@elementID" style="display:none">Like you</span>

                        }
                        else
                        {
                            <label>Beğendin</label>
                            <button type="button" id="like" onclick="like('@Model.Tweet.ID')" class="btn btn-default btn-xs" disabled="disabled"><i class="fa fa-thumbs-o-up"></i> Like</button>
                        }
                        
                    </div>
                    <!-- Box Comment -->
                    <!-- /.box -->
                </div>
            }
            <!-- /.col -->
        </div>
    </div>
</section>
<script src="~/Content/js/jquery.min.js"></script>
<script>

    function commentdelete(id) {
        $.ajax({
                    type: "POST",
                    url: "@Url.Action("DeleteComment","Comment")/" + id,
            success: function (result) {
                $("#a_" + id).fadeOut();
                    }
                })
        }

        function like(id) {
        $.ajax({
                    type: "POST",
                    dataType: "Json",
                    url: "@Url.Action("AddLike","Like")/" + id,
                    success: function (data) {
                if (data.isSuccess == true) {
                            $("#message" + id).removeAttr("");
                            $("#like").remove();
                            $("#message" + id).html("");
                            $("#message" + id).append(data.userMessage);
                    $("#commentcount").hide().fadeOut(2000);
                    $("#articlelist").append("<span class='pull-right text-muted' id='commentcount'>" + data.Likes + " likes  " + data.Comments + " comments</span>");
                        }
                        else {
                            $("#message" + id).removeAttr("");
                            $("#like").remove();
                            $("#message" + id).html("");
                            $("#message" + id).append(data.userMessage);
                        }
                    }
                })
        }


        function comment(articleID) {
            console.log(articleID);
            var commentText = $("#comment").val();

            $.ajax({
                    type: "POST",
                    dataType: "Json",
                    data: { userComment: commentText, id: articleID },
                    url: "@Url.Action("AddComment","Comment")",
                    success: function (data) {
                        if (data == true) {
                            $("#message").removeAttr("style");
                            $("#message").html("");
                            $("#message").append("Have Comments.").fadeIn(2000);

                            // Commentlerin hepsini silip tekrar listelemeyle geri çekmek gerekiyor.

                            commentdynamiclist(articleID);

                        }
                        else {
                            $("#message").removeAttr("style");
                            $("#message").html("");
                            $("#message").append("An error has occured.");
                        }
                    }
                })
    }

        function commentdynamiclist(id) {

            $.ajax({
                type: "POST",
                dataType: "Json",
                url: "@Url.Action("GetAtricleComment", "Comment")/" + id,
                success: function (data) {
                    if (data != null) {

                        //console.log(data.FirstName);
                        $("#dynamiccomment").append("<div class='box-comment' id='lastcomment'><!-- User image --><img class='img-circle img-sm' src='" + data.AppUserImagePath + "' alt='User Image'><div class='comment-text'><span class='username'>" + data.FirstName + " " + data.LastName + "<span class='text-muted pull-right'>" + data.CreatedDate + "<br /><a href='' id='commentdelete' type='button' class='btn btn-default btn-xs'><i class='fa fa-trash-o'></i></a><button type='button' id='edit' class='btn btn-default btn-xs'><i class='fa fa-edit'></i></button></span></span><!-- /.username -->" + data.Content + "</div></div>");
                        $("#commentcount").hide().fadeOut(2000);
                        $("#articlelist").append("<span class='pull-right text-muted' id='commentcount'>"+data.LikeCount+" likes  "+data.CommentCount+" comments</span>");
                        $("#comment").val("");
                        $("#message").fadeOut(2000);
                        $("#lastcomment").hide().fadeIn(2000);

                    }
                    else {

                    }
                }
            })
    }

</script>

LittleBird.UI/Areas/Member/Views/Tweet/Update.cshtml
@{
    ViewBag.Title = "Update";
    Layout = "~/Areas/Member/Views/Shared/MemberLayoutPage.cshtml";
}

<h2>Update</h2>